--- 
# This playbook is an example for deploying an EC2 instance
# Run this with ansible-playbook and supply the private key for your EC2 user
#
# ansible-playbook ec2-deploy.yml -v --private-key=/path/to/ec2/pri/key
#

# The play operates on the local (Ansible control) machine.
- name: Stage instance(s)
  hosts: local
  connection: local
  remote_user: root
  gather_facts: false

  vars:
      keypair: dev_ec2instances
      instance_type: t2.micro
      ec2_url: http://ec2.ap-southeast-1.amazonaws.com
      security_group: default
      image: ami-f95845ab

  # Launch 1 instance with the following parameters.  Register the output.

  tasks:
    - name: Launch instance
      ec2: keypair={{keypair}} group={{security_group}} ec2_url={{ec2_url}}
           instance_type={{instance_type}} image={{image}}
           wait=true count=1
      register: ec2

    # Use with_items to add each instances public IP to a new hostgroup for use in the next play.

    - name: Add new instances to host group
      add_host: hostname={{item.public_ip}} groupname=deploy
      with_items: ec2.instances

    - name: Wait for the instances to boot by checking the ssh port
      wait_for: host={{item.public_dns_name}} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    # Use the ec2_vol module to create volumes for attachment to each instance.
    # Use with_items to attach to each instance (by returned id) launched previously.

    - name: Create a volume and attach
      ec2_vol: volume_size=20 instance={{item.id}}
      with_items: ec2.instances

