---
- hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    ec2_url: "http://ec2.ap-southeast-1.amazonaws.com"
    ec2_id: "i-07d7dee1fs9fd8ee8"

  tasks:      
  - name: "Terminate tagged EC2 instances"
    ec2:
      state: "absent"
      ec2_url: "{{ ec2_url }}"
      instance_ids: "{{ ec2_id }}"
      wait: true
    delegate_to: "localhost"

- hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    ec2_url: "ec2_url: http://ec2.ap-southeast-1.amazonaws.com"
